### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)

### ISSUE THREAD

**Issue by shahnawazahmed88** [tekartik/sqflite#452]
Install app in Marshmallow
2.Getting Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.19.0-3.0.pre, on Linux, locale en_IN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!

**Comment by alextekartik** [comment]
I could not find a mashmallow emulator however I was able to install sqflite test app on a Lollipop emulator (5.1) without issue. Does it fail for you?

I'm not sure which app (yours?), device (emulator, real device?), flutter (dev only?, does it work on stable) you have tried and the steps I could try to reproduce the issue.

Also please look some tips here: https://github.com/tekartik/sqflite/blob/master/sqflite/doc/troubleshooting.md#missingpluginexception

**Comment by TheUnriashol** [comment]
I seem to be having this same issue. Only difference is that I am using background_fetch. Everything works fine while the app is open but as soon as I close the app completely and it runs a headless task I get this error:

```
06-10 03:13:43.695 9848-9848/com.example.example D/TSBackgroundFetch: - Background Fetch event received
06-10 03:13:43.695 9848-9848/com.example.example D/TSBackgroundFetch: �� [HeadlessTask flutter_background_fetch]
06-10 03:13:43.695 9848-9865/com.example.example I/flutter: [BackgroundFetch] Headless event received: flutter_background_fetch
06-10 03:13:43.695 9848-9865/com.example.example  E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #2      invokeMethod (package:sqflite/src/sqflite_impl.dart:17:13)
    #3      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:82:7)
    #4      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:25:35)
    #5      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:32)
    #6      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
    #7      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite_common/src/factory_mixin.dart:25:7)
    #8      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:143:26)
    #9      getDatabasesPath (package:sqflite/sqflite.dart:168:54)
    #10     DatabaseHelper.initDb (package:example/services/DatabaseHelper.dart:25:47)
    #11     DatabaseHelper.db (package:example/services/DatabaseHelper.dart:18:17)
    #12     DatabaseHelper.getIn (package:example/services/DatabaseHelper.dart:73:26)
    #13     backgroundFetchHeadlessTask (package:example/main.dart:18:18)
    #14     _headlessCallbackDispatcher.<anonymous closure> (package:background_fetch/background_fetch.dart:619:15)
    #15     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:409:55)
    #16     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:377:54)
    #17     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
    #18     _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
    #19     _rootRun (dart:async/zone.dart:1184:13)
    #20     _CustomZone.run (dart:async/zone.dart:1077:19)
    #21     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
    #22     _invoke3 (dart:ui/hooks.dart:289:10)
    #23     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)
```
I have created the Application.kt file which looks like this for me:

```
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import com.tekartik.sqflite.SqflitePlugin

class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
    }

    override fun registerWith(registry: PluginRegistry?) {
        SqflitePlugin.registerWith(registry?.registrarFor("com.tekartik.sqflite.SqflitePlugin"));
    }
}
```

And I have added the Application.kt file to my manifest like this:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.example">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <application
        android:name=".Application"
        android:label="Example"
        android:icon="@mipmap/launcher_icon">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">

...
```

I have also run:

```
flutter packages get

flutter pub get

flutter clean
```

But nothing has helped.

Any idea why I am still having this issue. Is it just simply impossible to run sqflite in a headless background task?

**Comment by alextekartik** [comment]
> Is it just simply impossible to run sqflite in a headless background task?

Unfortunately I'm not sure. I'm not familiar with background_fetch. What happens if you try to call another plugin (such as path_provider) as a simple test to validate that plugins can work in this situation?

**Comment by TristanPct** [comment]
I have the same issue using [flutter_cached_network_image](https://github.com/Baseflow/flutter_cached_network_image) in my app with [receive_sharing_intent](https://github.com/KasemJaffer/receive_sharing_intent) on Android.

First I launch my app, then I reduce it, then I launch another application to share content to my app.
This action wakes up my application but this error appears:
```
E/flutter (21497): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
```

The same error occurs when the application is completely inactive.

I tried to add an `Application.kt` with `SqflitePlugin.registerWith(registry?.registrarFor("com.tekartik.sqflite.SqflitePlugin"));` but it didn't work.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [version 10.0.19041.329], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.46.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by alextekartik** [comment]
@TristanPct 

> I tried to add an Application.kt

One thing I could think of: If you created the file, you also need to specify that it is indeed used. It means adding it in the manifest:
```dart
 <application
        android:name="your application class">
```

**Comment by TristanPct** [comment]
I forgot to mention it, but yes I added the reference in the manifest

```
 <application
        android:name=".Application">
```

and the `package` directive in the beginning of the `Àpplication.kt` file.

**Comment by alextekartik** [comment]
Maybe you can try:

```java
SqflitePlugin.registerWith(registry?.registrarFor("com.tekartik.sqflite"))
```

instead of
```java
SqflitePlugin.registerWith(registry?.registrarFor("com.tekartik.sqflite.SqflitePlugin"))
```

**Comment by TristanPct** [comment]
Unfortunately the issue is still there, even after a `flutter clean`

**Comment by TristanPct** [comment]
After further investigations, the issue seems to be much more related to [receive_sharing_intent](https://github.com/KasemJaffer/receive_sharing_intent) plugin which launch a new app on a share action (instead of using the one already launched).

So changing my manifest with:

```
<activity
        android:launchMode="singleTask"
```

prevents the MissingPluginException.

Thanks @alextekartik for your help.

**Comment by alextekartik** [comment]
@TristanPct  Thanks for sharing the info! I leave this bug open for some some time since when closed people are re-asking for the same problem. I'll try to package the various experiment info in the doc at some point.

**Comment by TheUnriashol** [comment]
@TristanPct In the end did you only change the launchMode or did you at the same time also register the plugin in the Application.kt file?

**Comment by TristanPct** [comment]
@TheUnriashol apparently the issue is caused by [receive_sharing_intent](https://github.com/KasemJaffer/receive_sharing_intent) plugin when I try to share a file from the download folder (https://github.com/KasemJaffer/receive_sharing_intent/issues/32) and the MissingPluginException on sqflite seems to be a side effect.

I tried to share a file from another source, without the Application.kt and with `launchMode` set to `singleTop` and I don't have this exception (but my app is opened twice, which is solved with `android:launchMode="singleTask"`).

The application opened twice doesn't seem to be a problem with this package.

**Comment by TheUnriashol** [comment]
@TristanPct Ok thanks for the additional info, my issue seems to be a bit different then.

**Comment by msndvlpr** [comment]
In my case I had this issue only in **release mode** with `flutter run --release` command, so removing `shrinkResources true` and `minifyEnabled true` lines in **build.gradle** file solved the problem.

**Comment by alextekartik** [comment]
@msndvlpr Thanks for the info. I will add this in the doc. There might be a solution using proguard (by excluding the SqflitePlugin class and maybe something else) too if anyone wants to take a stab at it!

**Comment by devUsama** [comment]
Got the same issue: 
**MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)**
Tried all the above proposed solutions but still getting the same issue, When trying to access the database in background services.

**Comment by dhushya** [comment]
I recently got this error and followed all steps in the `troubleshooting.md` file but could not fix it. I finally fixed it by disabling R8
`flutter build appbundle --no-shrink`

**Comment by Boehrsi** [comment]
Can also confirm that the `--no-shrink` solution currently seems like the only working fix / workaround, at least for me. 
I tried to build a release App Bundle with no success. With `flutter build appbundle --no-shrink` everything works well. 
As already mentioned I would also assume Proguard / R8 doesn't detect the calls to the Sqflite classes and just strips them away. If time allows I will have a look if I find some working Proguard / R8 rules to allow shrinking again.

**Comment by Boehrsi** [comment]
I think I found something, will continue testing and hopefully provide a PR or at least a full description tomorrow. :)

**Comment by alextekartik** [comment]
Great @Boehrsi I definitely think there must be a good solution and I guess mainly just keeping the `SqflitePlugin` should be enough.

**Comment by Boehrsi** [comment]
Was also my initial thought, but it seems (https://github.com/tekartik/sqflite/pull/546) that even less is required.

**Comment by Boehrsi** [comment]
As a small heads up for everyone who wants to use shrinking / obfuscation right now there is a simple "workaround" to get everything working. Just alter the `android/app/build.gradle` file of your app to use the default `proguard-android-optimize.txt`.

```
buildTypes {
        release {
            ...
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
            ...
        }
    }
```

For me this fixed the problems and it's also the default way which is suggested by the Android shrinking documentation anyhow (https://developer.android.com/studio/build/shrink-code). 
I tested this with a normal fat APK release build and also with an Android App Bundle build and it seems everything is working. As soon as my PR is merged or another fix for Sqflite is applied this shouldn't be mandatory anymore.

**Comment by ctcx** [comment]
I got help from this [link:](https://github.com/tekartik/sqflite/blob/master/sqflite/doc/troubleshooting.md#missingpluginexception)
I check my code,add line:
`GeneratedPluginRegistrant.registerWith(this);`
like this:
```
public class MainActivity extends FlutterActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        GeneratedPluginRegistrant.registerWith(this);
    }
}
```

**Comment by photoplyr** [comment]
I am seeing this issue again now that I am using Flutter 2

Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)

**Comment by Tak1za** [comment]
If you are still facing this issue, just go to android\app\build.gradle, and modify it so,
```
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug

            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
```

**Comment by namchuai** [comment]
I'm facing this issue even with debug build.

```
E/flutter (13314): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
E/flutter (13314): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
E/flutter (13314): <asynchronous suspension>
E/flutter (13314): #1      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7)
E/flutter (13314): <asynchronous suspension>
E/flutter (13314): #2      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:153)
E/flutter (13314): <asynchronous suspension>
E/flutter (13314): #3      SqfliteDatabaseFactoryMixin.fixPath (package:sqflite_common/src/factory_mixin.dart:180)
E/flutter (13314): <asynchronous suspension>
E/flutter (13314): #4      SqfliteDatabaseFactoryMixin.openDatabase (package:sqflite_common/src/factory_mixin.dart:85)
E/flutter (13314): <asynchronous suspension>
E/flutter (13314): #5      SqfliteDatabaseService.init (package:driveapp/service/local/sqflite_database_service.dart:18)
E/flutter (13314): <asynchronous suspension>
E/flutter (13314): #6      main (package:driveapp/main.dart:115)
E/flutter (13314): <asynchronous suspension>
E/flutter (13314):
```

My current flutter version:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.1 20D75 darwin-x64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)
```

**Comment by vishal-android-freak** [comment]
I am getting this error as soon as I am installing the [flutter_sounds](https://pub.dev/packages/sounds) package. Any of you facing a similar issue?

**Comment by Boehrsi** [comment]
@vishal-android-freak 
I also discovered (https://github.com/tekartik/sqflite/pull/546) that this problem seems to be related to the combination of different packages (in my case it was the `image_picker` package).

Have you already tried the workaround I mentioned here : https://github.com/tekartik/sqflite/issues/452#issuecomment-731835148 ?

**Comment by namchuai** [comment]
@Boehrsi Do you have any suggestion for my case above?

**Comment by vishal-android-freak** [comment]
> @vishal-android-freak
> I also discovered (#546) that this problem seems to be related to the combination of different packages (in my case it was the `image_picker` package).
> 
> Do you have `minifyEnabled / shrinkResources = true` in your debug builds? If yes, have you already tried the workaround I mentioned here: [#452 (comment)](https://github.com/tekartik/sqflite/issues/452#issuecomment-731835148) (adjusted to fit the debug build type of course)?

I have been facing this issue on debug and only on Android. Yes, I tried adding the proguard file but no difference :/ This is a major issue for me as the flutter_sound and Sqflite both are important for me!

**Comment by Boehrsi** [comment]
@vishal-android-freak That's actually quite bad :/. I was hoping that your problem is related to mine (minify / shrinking), as this is fixable quite easy. But it seems that it's the same error message, but a different problem source.

@namchuai Sadly not, I only encountered problems during builds with enabled minify / shrinking (normally only release builds). Debug was never a problem for me. Have you tried to create a new Flutter project and integrate `sqflite` there? Just asking because of the whole plugin wrapper upgrade, which happened some time ago and lead to some problems for older apps (https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects).

**Comment by paraslamsong** [comment]
Hello, is there any solution for iOS?
I am having same issue in iOS, android is working fine

**Comment by alexrainman** [comment]
I am facing this issue while trying to open the database on a WorkManager:

```
Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
```
None of the solutions work.

My code:

```
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
    var db = openDatabase(
      join(getDatabasesPath().toString(), 'db.sqlite'),
      version: 1,
    );
    return Future.value(true);
  });
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Workmanager().initialize(
    callbackDispatcher,
    isInDebugMode: true,
  );
  runApp(MyApp());
}
```

**Comment by ashikulislamdev** [comment]
> I have the same issue using [flutter_cached_network_image](https://github.com/Baseflow/flutter_cached_network_image) in my app with [receive_sharing_intent](https://github.com/KasemJaffer/receive_sharing_intent) on Android.
> 
> First I launch my app, then I reduce it, then I launch another application to share content to my app. This action wakes up my application but this error appears:
> 
> ```
> E/flutter (21497): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
> ```
> 
> The same error occurs when the application is completely inactive.
> 
> I tried to add an `Application.kt` with `SqflitePlugin.registerWith(registry?.registrarFor("com.tekartik.sqflite.SqflitePlugin"));` but it didn't work.
> 
> ```
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [version 10.0.19041.329], locale fr-FR)
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
> [√] Android Studio (version 3.6)
> [√] VS Code (version 1.46.1)
> [√] Connected device (1 available)
> 
> • No issues found!
> ```

Did you get any solution to this error?

**Comment by alextekartik** [comment]
Unfortunately sqflite is not supported (officially) in background isolate. Some people manage to use it but the solution is not safe regarding transaction. I don't have a proper solution at this time.

However I made some experiment here https://github.com/alextekartik/background_flutter_exp.dart/tree/main/packages/work_manager_exp4
where I access sqflite only from a background isolate. Sorry no doc...

**Comment by ShivuCode** [comment]
Error: MissingPluginException(No implementation found for method openDatabase on channel com.tekartik.sqflite)
whats solution for this

**Comment by Dieterbe** [comment]
Hi, I get this error when [following the flutter sqlite tutorial](https://docs.flutter.dev/cookbook/persistence/sqlite)
I'm a beginner so I don't know 100% how background isolates work, but seems to me it is breaking in the most barebones, standard way. at least the tutorial code seems really simple.

**Comment by bunyaminkirmizi** [comment]
> Hi, I get this error when [following the flutter sqlite tutorial](https://docs.flutter.dev/cookbook/persistence/sqlite) I'm a beginner so I don't know 100% how background isolates work, but seems to me it is breaking in the most barebones, standard way. at least the tutorial code seems really simple.
> 
> edit: i think it only happens when running as linux native app, not in the android emulator or native android device
> 
> edit 2: never mind, seems this is simply due to Linux target not being supported, as described in te docs.

I was running on windows and I had the same issue. It says it is supporting windows but probably there is no support for desktop applications.

**Comment by alextekartik** [comment]
Windows is not supported in sqflite. You have to use [sqflite_common_ffi](https://github.com/tekartik/sqflite/tree/master/sqflite_common_ffi)

**Comment by OptisolSivaG** [comment]
> In my case I had this issue only in **release mode** with `flutter run --release` command, so removing `shrinkResources true` and `minifyEnabled true` lines in **build.gradle** file solved the problem.

same for me also.. it was worked in debug mode. but on release mode also i have already have both of them 
//            isMinifyEnabled = false
//            isShrinkResources = false
as disabled. 

then why the issue still persists? any idea ?

**Comment by OptisolSivaG** [comment]
I am able to run android app on release mode with no error with this setup 

SOLUTION : 

import com.tekartik.sqflite.SqflitePlugin  // <------------------- add this ✅ 


class MainActivity: FlutterFragmentActivity() {


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
       // SqflitePlugin.registerWith(registrarFor("com.tekartik.sqflite.SqflitePlugin")) // <------------------- ❌ DO NOT add like this 
    }

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        flutterEngine.plugins.add(SqflitePlugin()) // <------------------- ✅ ADD like this 
      ..... 
} 
.... 
}
